version: "3.8"

services:
  postgresql:
    image: postgres:15-alpine
    container_name: msla-challenge-db
    environment:
      POSTGRES_DB: msla-challenge
      POSTGRES_USER: msla_user
      POSTGRES_PASSWORD: msla_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - msla-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U msla_user -d msla-challenge"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  msla-challenge-app:
    build: .
    container_name: msla-challenge-app
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/msla-challenge
      SPRING_DATASOURCE_USERNAME: msla_user
      SPRING_DATASOURCE_PASSWORD: msla_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EXTERNAL_API_BASE_URL: https://api.apilayer.com/exchangerates_data
      EXTERNAL_API_KEY: mock-api-key-for-development
    ports:
      - "8080:8080"
    networks:
      - msla-network
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  msla-network:
    driver: bridge
